#:schema https://docs.jj-vcs.dev/latest/config-schema.json
[user]
name = "Riley Bruins"
email = "ribru17@hotmail.com"

[ui]
default-command = "log"

[aliases]
checkout = ["edit"]
d = ["diff"]
e = ["edit"]
s = ["show"]
vi = ["util", "exec", "--", "bash", "-c", "jj diff --name-only | xargs nvim -p"]
# Refer to https://github.com/jj-vcs/jj/discussions/4974
sync = ["util", "exec", "--", "sh", "-c", "jj git fetch && jj rebase -d 'trunk()' -s 'roots(trunk()..) & mutable()'"]

[template-aliases]
default_commit_description = '''
"


JJ: Fixes #
"
'''

'format_short_signature(signature)' = 'signature'

[templates]
draft_commit_description = '''
concat(
  builtin_draft_commit_description,
  "\nJJ: ignore-rest\n",
  diff.git(),
)
'''
